[tool.poetry]
name = "WebdriverSession"
version = "0.1.0"
description = ""
authors = ["joismar <joismar@outlook.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
selenium = "^3.141.0"
pywin32 = "^301"
wget = "^3.2"
requests = "^2.25.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
